spring:
  application:
    name: projeto-empresa
  datasource:
    url: ${EMPRESA_DB:jdbc:mysql://localhost:3307/db_empresa?useTimezone=true&serverTimezone=UTC}
    username: ${EMPRESA_DB:root}
    password: ${EMPRESA_DB:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8096
